# Generated by Django 3.1.1 on 2020-12-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=100, null=True)),
                ('card_text', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'card_detail',
            },
        ),
    ]
